export default [
  {
    name: "base",
    data: {},
    items: [
      {
        name: "baked1",
        source: "/assets/textures/baked1.ktx2",
        type: "texture",
      },
      {
        name: "baked2",
        source: "/assets/textures/baked2.ktx2",
        type: "texture",
      },
      {
        name: "baked3",
        source: "/assets/textures/baked3.ktx2",
        type: "texture",
      },
      {
        name: "texture_paint",
        source: "/assets/textures/texture_paint.png",
        type: "texture",
      },
      { name: "_roomModel", source: "/assets/models/room.glb" },
      { name: "_roomModel2", source: "/assets/models/room2.glb" },
      { name: "_roomModel3", source: "/assets/models/room3_no_coffee.glb" },
      { name: "topChairModel", source: "/assets/models/topChair.glb" },
      { name: "rubiksCube", source: "/assets/models/Rubik.glb" },
      {
        name: "deskCoffeeReplacement",
        source: "/assets/models/deskCoffeeReplacement.glb",
      },
      { name: "zhangxuefeng", source: "/assets/models/zhangxuefeng.glb" },
      { name: "kadun", source: "/assets/models/kadun.glb" },
      { name: "paint", source: "/assets/models/paint.glb" },
      { name: "whiteboard", source: "/assets/models/whiteboard.glb" },
      { name: "leftMonitor", source: "/assets/models/leftMonitor.glb" },
      { name: "rightMonitor", source: "/assets/models/rightMonitor.glb" },
      { name: "linkedin", source: "/assets/models/linkedin.glb" },
      { name: "github", source: "/assets/models/github.glb" },
      { name: "itchio", source: "/assets/models/itchio.glb" },
      { name: "markerOpen", source: "assets/sounds/marker-open.mp3" },
      { name: "eraser", source: "assets/sounds/eraser.mp3" },
      { name: "mouseclick", source: "assets/sounds/mouseclick.ogg" },
      { name: "mouserelease", source: "assets/sounds/mouserelease.ogg" },
      { name: "start", source: "assets/sounds/start.mp3" },
      { name: "floral", source: "assets/sounds/floral.mp3" },
      { name: "whoosh", source: "assets/sounds/whoosh.mp3" },
      { name: "miaomiao", source: "assets/sounds/miaomiao.mp3" },
      { name: "bgm27", source: "assets/sounds/bgm27.opus" },
    ],
  },
];
